echo -n "1 - Hostname: "
echo -n "2 - Distribuição: "
echo -n "3 - Quantidade de processadores físicos: "
echo -n "4 - Quantidade de núcleos disponíveis no sistema: "
echo -n "5 - Modelo do processador: "
echo -n "6 - Quantidade de memória total: "
echo -n "7 - Quantidade de memória disponível: "
echo -n "8 - Informações sobre as placas de rede disponíveis no sistema: "
echo -n "9 - Informações de ip: "
echo ""
echo -n "10 - Informações sobre os dispositivos montados: "
echo ""
echo -n "11 - Quantidade de usuários: "
echo -n "12 - Quantidade de usuários comuns no sistema: "
